name : 'Custom github Action'
description: 'takes number and reurn the squred number'
inputs: 
  num:
    required: true
    default: "1"
 outputs: 
    num_squred:
    value: ${{ steps.get-squre.outputs.num_squared }}
runs:
  using: 'composite'
  steps: 
    - name: Install Python
      uses: action/setup-python@v4
      with:
        python -version: '3.10'
    - name: Install Denpendencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Pass Inputs to shell
      run: |
        echo"INPUT_NUM=${{ inputs.num }}" >> $GITHUB_ENV
      shell: bash
   - name: Fetch the number's suare
     id : get-squre
     run: python src/get_num_squre.py
     shell: bash
