name : 'custom github action'
description: 'takes number and reurn the squred number'
inputs: 
  num:
  required: true
  default: "1"
outputs: 
  num_squred:
    value: ${{ }}
runs:
  using: 'composite'
  steps: 
    - name: Install python
      uses: action/setup-python@v4
      with:
        python -version: '3.10'
    - name: Install denpendencies
      run: pip install -r requirements.txt
      shell: bash
      run:
        echo"INPUT_NUM${{ inputs.num }} >> $GITHUB_ENV
      shell: bash
   - name: fatch the number suare
     id : get-squre
     run: python src/get_num_squre.py
     shell: bash
